### ISSUE TITLE
`index-v0.5.1-node-v67-linux-x64.tar.gz` tar ball missing from releases

### ISSUE THREAD

**Issue by rudolph9** [IronCoreLabs/recrypt-node-binding#28]
```
$ yarn add @ironcorelabs/recrypt-node-binding
yarn add v1.17.3
warning package.json: No license field
warning No license field
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error /home/foobaruser/project/pondjs/node_modules/@ironcorelabs/recrypt-node-binding: Command failed.
Exit code: 1
Command: node-pre-gyp install
Arguments:
Directory: /home/foobaruser/project/pondjs/node_modules/@ironcorelabs/recrypt-node-binding
Output:
node-pre-gyp info it worked if it ends with ok
node-pre-gyp info using node-pre-gyp@0.13.0
node-pre-gyp info using node@11.15.0 | linux | x64
node-pre-gyp WARN Using request for node-pre-gyp https download
node-pre-gyp info check checked for "/home/foobaruser/project/pondjs/node_modules/@ironcorelabs/recrypt-node-binding/bin-package/index.node" (not found)
node-pre-gyp http GET https://github.com/IronCoreLabs/recrypt-node-binding/releases/download/0.5.1/index-v0.5.1-node-v67-linux-x64.tar.gz
node-pre-gyp http 404 https://github.com/IronCoreLabs/recrypt-node-binding/releases/download/0.5.1/index-v0.5.1-node-v67-linux-x64.tar.gz
node-pre-gyp ERR! install error
node-pre-gyp ERR! stack Error: 404 status code downloading tarball https://github.com/IronCoreLabs/recrypt-node-binding/releases/download/0.5.1/index-v0.5.1-node-v67-linux-x64.tar.gz
node-pre-gyp ERR! stack     at Request.<anonymous> (/home/foobaruser/project/pondjs/node_modules/node-pre-gyp/lib/install.js:149:27)
node-pre-gyp ERR! stack     at Request.emit (events.js:198:15)
node-pre-gyp ERR! stack     at Request.onRequestResponse (/home/foobaruser/project/pondjs/node_modules/request/request.js:1066:10)
node-pre-gyp ERR! stack     at ClientRequest.emit (events.js:193:13)
node-pre-gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:560:23)
node-pre-gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:113:17)
node-pre-gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:447:22)
node-pre-gyp ERR! stack     at TLSSocket.emit (events.js:193:13)
node-pre-gyp ERR! stack     at addChunk (_stream_readable.js:295:12)
node-pre-gyp ERR! stack     at readableAddChunk (_stream_readable.js:276:11)
node-pre-gyp ERR! System Linux 5.0.0-23-generic
node-pre-gyp ERR! command "/usr/bin/node" "/home/foobaruser/project/pondjs/node_modules/@ironcorelabs/recrypt-node-binding/node_modules/.bin/node-pre-gyp" "install"
node-pre-gyp ERR! cwd /home/foobaruser/project/pondjs/node_modules/@ironcorelabs/recrypt-node-binding
node-pre-gyp ERR! node -v v11.15.0
node-pre-gyp ERR! node-pre-gyp -v v0.13.0
node-pre-gyp ERR! not ok
404 status code downloading tarball https://github.com/IronCoreLabs/recrypt-node-binding/releases/download/0.5.1/index-v0.5.1-node-v67-linux-x64.tar.gz
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

**Comment by ernieturner** [comment]
As mentioned in [the changelog](https://github.com/IronCoreLabs/recrypt-node-binding/blob/master/CHANGELOG.md) we've removed support/artifact generation for Node 9 and 11 and added support for Node 12. If there's a pressing need for Node 11 support let us know, but it was [end-of-life a few months ago](https://github.com/nodejs/Release).
